### ISSUE TITLE
Multiple column headings

### ISSUE THREAD

**Issue by jillymackay** [ianhandel/bossier#4]
In importing a 'real' dataset where there were multiple columns labelled 'If you selected Other, please specify:' receive error:

> Error during wrapup: Columns [col names] must have unique names

Perhaps in the pad function there needs to something to make each name unique?

**Comment by ianhandel** [comment]
Now checks for non-unique tables for columns and suggests use of code or code and label
7689fc70a43f2a08e572d1162805b41de9886ebd
